//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int id { get; set; }
        public Nullable<int> Question { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Assessment { get; set; }
    
        public virtual Assessments Assessments { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
